# VS Docking Final results N-terminal

In [1]:
##Importing packages

import pandas as pd
import numpy as np
import math

## Ligand index

In [2]:
index_2=pd.read_csv('indice_2.csv')  
index_3=pd.read_csv('indice_3.csv')

In [3]:
index_2['Molecule'] = list(range(1, 311))
index_3['Molecule'] = list(range(1, 466))

## Autodock

In [4]:
autodock2=pd.read_csv('2_autodock.csv')  
autodock3=pd.read_csv('3_autodock.csv')

In [5]:
autodock2['Unnamed: 1']=autodock2['Unnamed: 1'].str.replace(".csv :", "")
autodock3['Unnamed: 1']=autodock3['Unnamed: 1'].str.replace(".csv :", "")

In [6]:
autodock2=autodock2.rename(columns={'Unnamed: 1': 'Molecule'})
autodock3=autodock3.rename(columns={'Unnamed: 1': 'Molecule'})

In [7]:
autodock2.Molecule=autodock2.Molecule.astype('int64')
autodock3.Molecule=autodock3.Molecule.astype('int64')

In [8]:
autodock2=index_2.merge(autodock2, on='Molecule', how='left')
autodock3=index_3.merge(autodock3, on='Molecule', how='left')

In [9]:
autodock2=autodock2.sort_values(by=[('lowest_binding_energy')])
autodock3=autodock3.sort_values(by=[('lowest_binding_energy')])

In [10]:
autodock2=autodock2.drop_duplicates(subset=['Label'])
autodock3=autodock3.drop_duplicates(subset=['Label'])

In [11]:
autodock2.Molecule=autodock2.Molecule.div(2).apply(np.ceil).astype('int64')
autodock3.Molecule=autodock3.Molecule.div(3).apply(np.ceil).astype('int64')

In [12]:
autodock2.head(n=20)

,Label,Molecule,Output,cluster_rank,lowest_binding_energy,mean_binding_energy,num_in_clus,run
23,52948856,12,156,1,-12.31,-10.41,2,34
4,118707521,3,255,1,-11.69,-11.12,15,29
11,76325328,6,23,1,-11.49,-10.79,18,42
258,ZINC000106382957,130,177,1,-11.38,-10.31,18,47
26,52944903,14,189,1,-11.20,-10.57,6,39
159,118328,80,68,1,-11.18,-10.77,3,3
215,ZINC000019893747,108,130,1,-11.13,-10.69,3,10
102,2733787,52,5,1,-11.12,-10.53,6,7
145,202260,73,52,1,-10.95,-9.30,12,28
148,198514,75,55,1,-10.94,-10.36,18,37
165,99461,83,74,1,-10.89,-9.32,9,46
276,ZINC000257347638,139,197,1,-10.83,-10.75,13,49
90,5462244,46,301,1,-10.81,-9.75,33,33
206,ZINC000015205840,104,120,1,-10.81,-9.61,10,7
244,ZINC000101361998,123,162,1,-10.77,-9.49,5,8
17,57339290,9,89,1,-10.77,-9.76,22,9
141,312829,71,48,1,-10.73,-9.75,16,19
238,ZINC000101135603,120,155,1,-10.73,-9.34,20,47
153,129618,77,61,1,-10.70,-9.56,19,2
271,ZINC000257346145,136,192,1,-10.69,-10.64,47,15

In [13]:
autodock3.head(n=20)

,Label,Molecule,Output,cluster_rank,lowest_binding_energy,mean_binding_energy,num_in_clus,run
15,76325328,6,67,1,-11.60,-11.05,9,48
7,118707521,3,443,1,-11.58,-10.70,9,37
219,198515,74,135,1,-11.54,-10.22,4,33
238,118328,80,155,1,-11.51,-10.99,9,20
154,2733787,52,62,1,-11.43,-10.40,6,47
210,312829,71,125,1,-11.39,-10.63,6,23
224,198514,75,140,1,-11.36,-10.52,14,18
310,ZINC000015205840,104,236,1,-11.34,-10.56,13,37
216,202260,73,131,1,-11.32,-9.32,14,26
370,ZINC000102205030,124,302,1,-11.18,-9.94,15,46
323,ZINC000019893747,108,250,1,-11.18,-10.09,8,18
358,ZINC000101135603,120,288,1,-11.14,-9.85,22,25
229,129618,77,146,1,-11.13,-10.20,6,18
368,ZINC000101361998,123,299,1,-11.12,-9.77,7,35
248,99461,83,166,1,-11.09,-9.59,21,14
388,ZINC000106382957,130,321,1,-11.07,-10.03,21,48
245,102416,82,163,1,-10.99,-10.57,22,16
418,ZINC000257347639,140,355,1,-10.92,-10.78,14,39
416,ZINC000257347638,139,353,1,-10.88,-10.18,21,41
241,112106,81,159,1,-10.81,-10.04,4,8

In [14]:
autodock2.head(n=20).to_csv('autodock2_final.csv')

In [15]:
autodock3.head(n=20).to_csv('autodock3_final.csv')

## Vina

In [16]:
vina2=pd.read_csv('2_vina.csv')  
vina3=pd.read_csv('3_vina.csv')

In [17]:
vina2

      Number Molecule  affinity_(kcal/mol)  rmsd_lb  rmsd_ub
0          0   Lig100                 -5.4    0.000    0.000
1          1   Lig100                 -5.3    7.690   11.008
2          2   Lig100                 -5.3    6.150   10.238
3          3   Lig100                 -5.3    6.385   10.475
4          4   Lig100                 -5.2    8.799   12.204
...      ...      ...                  ...      ...      ...
6180    6180     Lig9                 -4.4    6.924    9.088
6181    6181     Lig9                 -4.3    3.055    6.297
6182    6182     Lig9                 -4.2    4.589    6.968
6183    6183     Lig9                 -4.2    3.043    5.683
6184    6184     Lig9                 -4.2    4.692    6.358

[6185 rows x 5 columns]

In [18]:
vina2['Molecule']=vina2['Molecule'].str.replace("Lig", "")
vina3['Molecule']=vina3['Molecule'].str.replace("Lig", "")

In [19]:
vina2=vina2.drop(columns=['Number'])
vina3=vina3.drop(columns=['Number'])

In [20]:
vina2.Molecule=vina2.Molecule.astype('int64')
vina3.Molecule=vina3.Molecule.astype('int64')

In [21]:
vina2=index_2.merge(vina2, on='Molecule', how='left')
vina3=index_3.merge(vina3, on='Molecule', how='left')

In [22]:
vina2=vina2.sort_values(by=[('affinity_(kcal/mol)')])
vina3=vina3.sort_values(by=[('affinity_(kcal/mol)')])

In [23]:
vina2=vina2.drop_duplicates(subset=['Label'])
vina3=vina3.drop_duplicates(subset=['Label'])

In [24]:
vina2.Molecule=vina2.Molecule.div(2).apply(np.ceil).astype('int64')
vina3.Molecule=vina3.Molecule.div(3).apply(np.ceil).astype('int64')

In [25]:
vina2.head(n=20)

                 Label  Molecule  affinity_(kcal/mol)  rmsd_lb  rmsd_ub
81           118707521         3                 -8.1    3.502    5.533
200           76325328         6                 -8.0    0.000    0.000
5528  ZINC000257347638       139                 -7.9    0.000    0.000
539           52944903        14                 -7.8    0.000    0.000
440           52948856        12                 -7.6    0.000    0.000
3174            118328        80                 -7.5    0.000    0.000
4888  ZINC000101361998       123                 -7.5    0.000    0.000
500           52944904        13                 -7.4    0.000    0.000
3551             29327        90                 -7.3    0.000    0.000
2054           2733787        52                 -7.2    0.000    0.000
839           45266822        22                 -7.0    0.000    0.000
4508  ZINC000077269504       114                 -7.0    0.000    0.000
1119          25243963        29                 -7.0    0.000    0.000
4589  ZINC000100342293       116                 -6.9    0.030    1.057
4768  ZINC000101135603       120                 -6.9    0.000    0.000
799           45357367        21                 -6.9    0.000    0.000
4448  ZINC000044021353       112                 -6.9    0.000    0.000
3911  ZINC000004027857        99                 -6.8    3.757    8.754
5646  ZINC000307565252       142                 -6.8    0.000    0.000
3214            112106        81                 -6.8    0.000    0.000

In [26]:
vina3.head(n=20)

                 Label  Molecule  affinity_(kcal/mol)  rmsd_lb  rmsd_ub
300           76325328         6                 -8.1    0.000    0.000
818           52944903        14                 -7.8    1.627    2.586
758           52944904        13                 -7.6    0.000    0.000
4745            118328        80                 -7.6    0.000    0.000
120          118707521         3                 -7.5    0.000    0.000
3092           2733787        52                 -7.5    0.000    0.000
5324             29327        90                 -7.4    0.000    0.000
678           52948856        12                 -7.4    0.000    0.000
1456          44341508        25                 -7.3    0.000    0.000
8336  ZINC000257347639       140                 -7.3    0.000    0.000
0            134695375         1                 -7.2    0.000    0.000
4785            112106        81                 -7.1    0.000    0.000
8276  ZINC000257347638       139                 -7.1    0.000    0.000
3152           2733335        53                 -7.1    0.000    0.000
5942  ZINC000004027859       100                 -7.0    0.000    0.000
6878  ZINC000100342293       116                 -7.0    0.000    0.000
8673  ZINC000575124622       146                 -7.0    0.000    0.000
6779  ZINC000077269504       114                 -7.0    0.000    0.000
1257          45266822        22                 -7.0    0.000    0.000
7298  ZINC000101361998       123                 -7.0    0.000    0.000

In [27]:
vina2.head(n=20).to_csv('vina2_final.csv')

In [28]:
vina3.head(n=20).to_csv('vina3_final.csv')

## Smina

In [29]:
smina2=pd.read_csv('2_smina.csv')  
smina3=pd.read_csv('3_smina.csv')

In [30]:
smina2=smina2.drop(columns=['Number'])
smina3=smina3.drop(columns=['Number'])

In [31]:
smina2['Molecule']=smina2['Molecule'].str.replace("Lig", "")
smina3['Molecule']=smina3['Molecule'].str.replace("Lig", "")

In [32]:
smina2.Molecule=smina2.Molecule.astype('int64')
smina3.Molecule=smina3.Molecule.astype('int64')

In [33]:
smina2=index_2.merge(smina2, on='Molecule', how='left')
smina3=index_3.merge(smina3, on='Molecule', how='left')

In [34]:
smina2=smina2.sort_values(by=[('Affinity')])
smina3=smina3.sort_values(by=[('Affinity')])

In [35]:
smina2=smina2.drop_duplicates(subset=['Label'])
smina3=smina3.drop_duplicates(subset=['Label'])

In [36]:
smina2.Molecule=smina2.Molecule.div(2).apply(np.ceil).astype('int64')
smina3.Molecule=smina3.Molecule.div(3).apply(np.ceil).astype('int64')

In [37]:
smina2.head(n=20)

                  Label  Molecule  Affinity
1207           52944904        13 -8.227994
1255           52944903        14 -8.207546
1113           52948856        12 -8.123951
242           118707521         3 -7.948771
482            76325328         6 -7.473453
8629              29327        90 -7.283598
4935            2733787        52 -7.079888
2322           44341508        25 -7.035575
7695             118328        80 -6.882257
2710           25243963        29 -6.744600
4574            5284365        48 -6.703381
10829  ZINC000044021353       112 -6.675403
1943           45357367        21 -6.668245
6140             440235        64 -6.642325
11472  ZINC000101073479       119 -6.546087
7745             112106        81 -6.534222
8441              82313        88 -6.392160
99            129878031         2 -6.391531
681            57339292         8 -6.333513
2891           24847493        31 -6.326365

In [38]:
smina3.head(n=10)

           Label  Molecule  Affinity
1883    52944903        14 -8.583083
1596    52948856        12 -8.386328
1733    52944904        13 -8.195645
268    118707521         3 -7.727368
707     76325328         6 -7.643952
3559    44341508        25 -7.349305
12953      29327        90 -7.320251
7486     2733787        52 -7.092809
7636     2733335        53 -6.835548
11548     118328        80 -6.810194

In [39]:
smina2.head(n=20).to_csv('smina2_final.csv')

In [40]:
smina3.head(n=20).to_csv('smina3_final.csv')

## PLANTS

In [41]:
plants2=pd.read_csv('2_plants.csv')  
plants3=pd.read_csv('3_plants.csv')

In [42]:
plants2=plants2.rename(columns={'LIGAND_ENTRY':'Label'})
plants3=plants3.rename(columns={'LIGAND_ENTRY':'Label'})

In [43]:
plants2['Label']=plants2['Label'].str.replace("_entry", "")
plants3['Label']=plants3['Label'].str.replace("_entry", "")

In [44]:
plants2['Label']=plants2['Label'].str.replace("_conf", "")
plants3['Label']=plants3['Label'].str.replace("_conf", "")

In [45]:
plants2=plants2.drop(columns=['Unnamed: 0','SCORE_NORM_HEVATOMS','SCORE_RB_PEN','SCORE_NORM_CRT_WEIGHT','SCORE_RB_PEN_NORM_CRT_HEVATOMS','SCORE_NORM_CONTACT','EVAL','TIME'])
plants3=plants3.drop(columns=['Unnamed: 0','SCORE_NORM_HEVATOMS','SCORE_RB_PEN','SCORE_NORM_CRT_WEIGHT','SCORE_RB_PEN_NORM_CRT_HEVATOMS','SCORE_NORM_CONTACT','EVAL','TIME'])

In [46]:
plants2[['Label','Molecule','Conformation']]=plants2.Label.apply(lambda x: pd.Series(str(x).split("_")))
plants3[['Label','Molecule','Conformation']]=plants3.Label.apply(lambda x: pd.Series(str(x).split("_")))

In [47]:
plants2=plants2.sort_values(by=[('TOTAL_SCORE')])
plants3=plants3.sort_values(by=[('TOTAL_SCORE')])

In [48]:
plants2=plants2.drop_duplicates(subset=['Label'])
plants3=plants3.drop_duplicates(subset=['Label'])

In [49]:
plants2.Molecule=plants2.Molecule.astype('int64')
plants3.Molecule=plants3.Molecule.astype('int64')

In [50]:
plants2.Molecule=plants2.Molecule.div(2).apply(np.ceil).astype('int64')
plants3.Molecule=plants3.Molecule.div(3).apply(np.ceil).astype('int64')

In [51]:
plants2.head(n=20)

,Label,TOTAL_SCORE,SCORE_NORM_CRT_HEVATOMS,SCORE_NORM_WEIGHT,Molecule,Conformation
0,52944903,-84.1483,-25.9748,-0.179969,14,01
1,ZINC000101135603,-80.8392,-26.3121,-0.201370,120,01
2,4282259,-78.4517,-28.4356,-0.263879,49,01
3,7067772,-77.6327,-29.6224,-0.291591,41,01
4,82313,-76.6003,-31.0599,-0.346279,88,01
5,ZINC000101361998,-76.5119,-24.9036,-0.189658,123,01
6,52948856,-76.4950,-23.1668,-0.154341,12,01
7,44630437,-76.2931,-30.2769,-0.324326,24,01
8,ZINC000100815672,-76.1927,-26.0575,-0.208573,118,01
9,29327,-75.7072,-28.8877,-0.285440,90,01
10,52944904,-75.4962,-23.0800,-0.156763,13,01
11,2733335,-75.4408,-28.7861,-0.284435,53,01
12,129878031,-75.3248,-29.2947,-0.302191,2,01
13,ZINC000100656214,-75.2785,-26.8656,-0.241798,117,01
14,25243963,-75.1761,-28.1727,-0.251280,29,01
15,440235,-74.9634,-28.0930,-0.249660,64,01
16,445621,-74.2840,-32.4465,-0.412272,59,01
17,102416,-74.1615,-25.7104,-0.216654,82,01
19,ZINC000101073479,-73.9855,-26.8168,-0.248856,119,01
20,ZINC000106382931,-73.8849,-26.3683,-0.234337,129,01

In [52]:
plants3.head(n=20)

,Label,TOTAL_SCORE,SCORE_NORM_CRT_HEVATOMS,SCORE_NORM_WEIGHT,Molecule,Conformation
0,ZINC000101361998,-86.1547,-28.0422,-0.213561,123,01
1,2733335,-81.4698,-31.0866,-0.306004,53,01
2,52944904,-78.6695,-24.0501,-0.163011,13,01
3,44630437,-78.5639,-31.1781,-0.333979,24,01
4,ZINC000003956714,-77.9832,-27.8309,-0.250486,98,01
5,12600646,-77.8985,-28.6981,-0.248323,36,01
6,ZINC000100815672,-76.7933,-26.2629,-0.210218,118,01
7,82313,-76.4892,-31.0148,-0.345776,88,01
8,45266822,-76.3007,-26.0945,-0.197498,22,01
9,447448,-75.7599,-29.4639,-0.303937,57,01
10,2733787,-75.5739,-25.1913,-0.199215,52,01
13,7067772,-75.3351,-28.7457,-0.282962,41,01
14,ZINC000252694384,-75.1656,-26.4308,-0.225440,135,01
15,24139,-74.9572,-30.3937,-0.338851,92,01
16,ZINC000101136391,-74.8822,-28.0626,-0.277034,121,01
20,2801971,-74.6980,-26.6584,-0.239934,51,01
21,5284365,-74.4267,-27.4190,-0.237256,48,01
22,ZINC000015205946,-74.2750,-25.7497,-0.216986,105,01
23,45266741,-74.2511,-32.4321,-0.412089,23,01
24,ZINC000100656214,-74.2104,-26.4844,-0.238367,117,01

In [53]:
plants2.head(n=20).to_csv('plants2_final.csv')

In [54]:
plants3.head(n=20).to_csv('plants3_final.csv')

## rDock

In [55]:
rdock2=pd.read_csv('2_rdock.csv',delim_whitespace=True)  
rdock3=pd.read_csv('3_rdock.csv',delim_whitespace=True)

In [56]:
rdock2=rdock2.drop(columns=['REC'])
rdock3=rdock3.drop(columns=['REC'])

In [57]:
rdock2=rdock2.rename(columns={'_TITLE1':'Label'})
rdock3=rdock3.rename(columns={'_TITLE1':'Label'})

In [58]:
rdock2=index_2.merge(rdock2, on='Label', how='left')
rdock3=index_3.merge(rdock3, on='Label', how='left')

In [59]:
rdock2=rdock2.sort_values(by=[('TOTAL')])
rdock3=rdock3.sort_values(by=[('TOTAL')])

In [60]:
rdock2=rdock2.drop_duplicates(subset=['Label'])
rdock3=rdock3.drop_duplicates(subset=['Label'])

In [61]:
rdock2.Molecule=rdock2.Molecule.div(2).apply(np.ceil).astype('int64')
rdock3.Molecule=rdock3.Molecule.div(3).apply(np.ceil).astype('int64')

In [62]:
rdock2.head(n=20)

                  Label  Molecule   TOTAL   INTER  INTRA  RESTR     VDW
4592           45266741        23 -32.857 -28.996 -2.872    0.0 -14.000
8184            7067772        41 -32.580 -28.732 -4.297    0.0 -16.465
11312            447448        57 -32.409 -28.465 -3.450    0.0 -16.696
13233            439213        67 -31.102 -28.986 -1.587    0.0 -13.996
4174           45357367        21 -30.958 -31.496  0.968    0.0 -16.593
18214             24139        92 -30.564 -28.913 -1.120    0.0 -15.774
17949             29327        90 -30.120 -26.028 -3.639    0.0 -16.755
7126           12600646        36 -29.838 -28.270 -0.443    0.0 -18.758
223           129878031         2 -28.773 -24.820 -3.802    0.0 -16.819
23671  ZINC000101073479       119 -28.704 -25.101 -4.196    0.0 -19.546
17546             82313        88 -27.944 -26.261 -0.579    0.0 -16.015
11904            441477        60 -27.936 -23.867 -3.059    0.0 -12.527
4738           44630437        24 -27.755 -26.267 -0.451    0.0 -14.346
11628            445621        59 -27.681 -26.039 -0.605    0.0 -13.660
198           134695375         1 -27.599 -24.950 -1.526    0.0 -16.127
8401            6713972        43 -27.233 -28.000  1.223    0.0 -16.239
5518           42612215        28 -27.189 -27.350  0.613    0.0 -14.740
12911            440049        65 -27.151 -25.963 -0.144    0.0 -12.495
15122            193108        76 -27.034 -24.418 -2.532    0.0 -16.464
7636           11096158        39 -26.924 -26.896  0.198    0.0 -13.364

In [63]:
rdock3.head(n=20)

           Label  Molecule   TOTAL   INTER  INTRA  RESTR     VDW
10257   45266741        23 -33.636 -28.838 -4.597    0.0 -14.027
25291     447448        57 -31.122 -28.095 -3.122    0.0 -16.563
41322      24139        92 -30.556 -28.719 -0.726    0.0 -15.644
10490   44630437        24 -30.484 -28.940 -1.465    0.0 -15.243
682    129878031         2 -30.327 -25.701 -5.267    0.0 -15.163
26165     445621        59 -29.702 -25.702 -2.875    0.0 -14.991
26552     441477        60 -29.694 -27.146 -2.251    0.0 -13.466
21210    5284365        48 -29.625 -27.386 -2.802    0.0 -18.188
9416    45357367        21 -29.451 -21.573 -8.027    0.0 -15.791
19113    6713972        43 -29.407 -25.129 -4.057    0.0 -14.627
29746     439213        67 -29.329 -25.004 -3.332    0.0 -12.698
11840   44119773        27 -29.214 -25.580 -2.648    0.0 -15.474
344    134695375         1 -29.000 -23.642 -4.316    0.0 -15.863
5662    52944904        13 -28.813 -23.256 -6.510    0.0 -26.590
39455      82313        88 -28.594 -26.491 -2.142    0.0 -16.055
24397     449462        55 -28.189 -22.891 -4.983    0.0 -14.213
40370      29327        90 -27.669 -25.509 -1.044    0.0 -15.588
6488    51351654        15 -27.624 -26.746  0.002    0.0 -14.558
18345    7067772        41 -27.569 -25.432 -1.983    0.0 -13.516
19512    6420074        44 -27.426 -22.933 -3.375    0.0 -14.170

In [64]:
rdock2.head(n=20).to_csv('rdock2_final.csv')

In [65]:
rdock3.head(n=20).to_csv('rdock3_final.csv')

# Parsing the preprocessing data
## Two variants

In [66]:
ad2 =autodock2.filter(['Label','Molecule'], axis=1)
ad2=ad2.rename(columns={'Label':'Label_ad','Molecule':'Molecule_ad'})

vin2=vina2.filter(['Label','Molecule'], axis=1)
vin2=vin2.rename(columns={'Label':'Label_vin','Molecule':'Molecule_vin'})

smin2=smina2.filter(['Label','Molecule'], axis=1)
smin2=smin2.rename(columns={'Label':'Label_smin','Molecule':'Molecule_smin'})

plan2=plants2.filter(['Label','Molecule'], axis=1)
plan2=plan2.rename(columns={'Label':'Label_plan','Molecule':'Molecule_plan'})

rdoc2=rdock2.filter(['Label','Molecule'], axis=1)
rdoc2=rdoc2.rename(columns={'Label':'Label_rdoc','Molecule':'Molecule_rdoc'})

In [67]:
total_2=pd.concat([ad2.reset_index(drop=True), vin2.reset_index(drop=True), smin2.reset_index(drop=True), plan2.reset_index(drop=True), rdoc2.reset_index(drop=True)],axis=1)

In [68]:
total_2.head(10)

,Label_ad,Molecule_ad,Label_vin,Molecule_vin,Label_smin,Molecule_smin,Label_plan,Molecule_plan,Label_rdoc,Molecule_rdoc
0,52948856,12,118707521,3,52944904,13,52944903,14,45266741,23
1,118707521,3,76325328,6,52944903,14,ZINC000101135603,120,7067772,41
2,76325328,6,ZINC000257347638,139,52948856,12,4282259,49,447448,57
3,ZINC000106382957,130,52944903,14,118707521,3,7067772,41,439213,67
4,52944903,14,52948856,12,76325328,6,82313,88,45357367,21
5,118328,80,118328,80,29327,90,ZINC000101361998,123,24139,92
6,ZINC000019893747,108,ZINC000101361998,123,2733787,52,52948856,12,29327,90
7,2733787,52,52944904,13,44341508,25,44630437,24,12600646,36
8,202260,73,29327,90,118328,80,ZINC000100815672,118,129878031,2
9,198514,75,2733787,52,25243963,29,29327,90,ZINC000101073479,119

In [69]:
total_2.head(n=20).to_csv('total_2.csv')

### ECR function two variants

In [70]:
numeros2 = list(index_2.loc[:,"Molecule"].values)

In [71]:
cons2_ad = list(total_2.loc[:, "Molecule_ad"].values)
ind2_ad = [cons2_ad.index(num)+1 for num in numeros2 if num in cons2_ad]

cons2_vin = list(total_2.loc[:, "Molecule_vin"].values)
ind2_vin = [cons2_vin.index(num)+1 for num in numeros2 if num in cons2_vin]

cons2_smin = list(total_2.loc[:, "Molecule_smin"].values)
ind2_smin = [cons2_smin.index(num)+1 for num in numeros2 if num in cons2_smin]

cons2_plan = list(total_2.loc[:, "Molecule_plan"].values)
ind2_plan = [cons2_plan.index(num)+1 for num in numeros2 if num in cons2_plan]

cons2_rdoc = list(total_2.loc[:, "Molecule_rdoc"].values)
ind2_rdoc = [cons2_rdoc.index(num)+1 for num in numeros2 if num in cons2_rdoc]

In [72]:
ecr2 = pd.DataFrame(
    {'ad2': ind2_ad,
     'vin2': ind2_vin,
     'smin2': ind2_smin,
     'plan2': ind2_plan,
     'rdoc2': ind2_rdoc
    })

In [73]:
ecr2

     ad2  vin2  smin2  plan2  rdoc2
0    107    30    145     91     15
1     99    84     18     13      9
2      2     1      4    154     26
3     76    64     48    120    120
4     83   124     93    119     85
..   ...   ...    ...    ...    ...
150   97   139    118     42     37
151   78   114     94     83     97
152  103    95     66     46     95
153  113   152    153    137     63
154   54    36    130    135    144

[155 rows x 5 columns]

In [74]:
ecr2=ecr2.apply(lambda x: np.exp(-x/20)/20, axis=1)
ecr2["ECR"] = ecr2.sum(axis=1)
ecr2["Molecule"]=list(range(1, 156))

In [75]:
ecr2

          ad2      vin2     smin2     plan2     rdoc2       ECR  Molecule
0    0.000237  0.011157  0.000036  0.000528  0.023618  0.035576         1
1    0.000354  0.000750  0.020328  0.026102  0.031881  0.079416         2
2    0.045242  0.047561  0.040937  0.000023  0.013627  0.147389         3
3    0.001119  0.002038  0.004536  0.000124  0.000124  0.007940         4
4    0.000788  0.000101  0.000478  0.000130  0.000713  0.002211         5
..        ...       ...       ...       ...       ...       ...       ...
150  0.000391  0.000048  0.000137  0.006123  0.007862  0.014561       151
151  0.001012  0.000167  0.000455  0.000788  0.000391  0.002814       152
152  0.000290  0.000433  0.001844  0.005013  0.000433  0.008012       153
153  0.000176  0.000025  0.000024  0.000053  0.002143  0.002420       154
154  0.003360  0.008265  0.000075  0.000059  0.000037  0.011796       155

[155 rows x 7 columns]

In [76]:
labelecr_2=index_2.drop_duplicates(subset=['Label']).drop(columns=['Molecule'])
labelecr_2["Molecule"]=list(range(1, 156))

In [77]:
ecr2=ecr2[['ECR','Molecule']]
ecr2=labelecr_2.merge(ecr2, on='Molecule', how='left')

In [78]:
ecr2=ecr2.sort_values(by=['ECR'],ascending=False)
ecr2['Molecule_par']=ecr2['Molecule'].apply(lambda x: x*2)
ecr2['Molecule_impar']=ecr2['Molecule'].apply(lambda x: x*2-1)

In [79]:
ecr2.head(n=20)

                Label  Molecule       ECR  Molecule_par  Molecule_impar
13           52944903        14  0.178504            28              27
11           52948856        12  0.164811            24              23
2           118707521         3  0.147389             6               5
89              29327        90  0.134856           180             179
79             118328        80  0.133524           160             159
5            76325328         6  0.131143            12              11
12           52944904        13  0.127483            26              25
122  ZINC000101361998       123  0.107107           246             245
51            2733787        52  0.101424           104             103
87              82313        88  0.099862           176             175
20           45357367        21  0.095585            42              41
40            7067772        41  0.095416            82              81
28           25243963        29  0.093085            58              57
119  ZINC000101135603       120  0.092799           240             239
118  ZINC000101073479       119  0.086799           238             237
138  ZINC000257347638       139  0.082926           278             277
1           129878031         2  0.079416             4               3
23           44630437        24  0.079315            48              47
80             112106        81  0.076756           162             161
48            4282259        49  0.066996            98              97

In [80]:
ecr2.to_csv('ecr2N.csv')

# Parsing the preprocessing data
## Three variants

In [81]:
ad3 =autodock3.filter(['Label','Molecule'], axis=1)
ad3=ad3.rename(columns={'Label':'Label_ad','Molecule':'Molecule_ad'})

vin3=vina3.filter(['Label','Molecule'], axis=1)
vin3=vin3.rename(columns={'Label':'Label_vin','Molecule':'Molecule_vin'})

smin3=smina3.filter(['Label','Molecule'], axis=1)
smin3=smin3.rename(columns={'Label':'Label_smin','Molecule':'Molecule_smin'})

plan3=plants3.filter(['Label','Molecule'], axis=1)
plan3=plan3.rename(columns={'Label':'Label_plan','Molecule':'Molecule_plan'})

rdoc3=rdock3.filter(['Label','Molecule'], axis=1)
rdoc3=rdoc3.rename(columns={'Label':'Label_rdoc','Molecule':'Molecule_rdoc'})

In [82]:
total_3=pd.concat([ad3.reset_index(drop=True), vin3.reset_index(drop=True), smin3.reset_index(drop=True), plan3.reset_index(drop=True), rdoc3.reset_index(drop=True)],axis=1)

In [83]:
total_3.head(107)

,Label_ad,Molecule_ad,Label_vin,Molecule_vin,Label_smin,Molecule_smin,Label_plan,Molecule_plan,Label_rdoc,Molecule_rdoc
0,76325328,6,76325328,6,52944903,14,ZINC000101361998,123,45266741,23
1,118707521,3,52944903,14,52948856,12,2733335,53,447448,57
2,198515,74,52944904,13,52944904,13,52944904,13,24139,92
3,118328,80,118328,80,118707521,3,44630437,24,44630437,24
4,2733787,52,118707521,3,76325328,6,ZINC000003956714,98,129878031,2
...,...,...,...,...,...,...,...,...,...,...
102,ZINC000616582813,150,49859685,16,449462,55,6971258,42,ZINC000004027859,100
103,ZINC000100342293,116,ZINC000616582904,151,6971258,42,ZINC000100342293,116,122253,79
104,447448,57,24154,91,440049,65,127132,78,82398,87
105,644170,54,739,96,ZINC000102205030,124,46174147,18,25243937,30
106,254124,72,5462244,46,ZINC000616583781,153,ZINC000004027857,99,45934204,19

In [84]:
total_3.head(n=20).to_csv('total_3.csv')

### ECR function three variants

In [85]:
numeros3 = list(index_3.loc[:,"Molecule"].values)

In [86]:
cons3_ad = list(total_3.loc[:, "Molecule_ad"].values)
ind3_ad = [cons3_ad.index(num)+1 for num in numeros3 if num in cons3_ad]

cons3_vin = list(total_3.loc[:, "Molecule_vin"].values)
ind3_vin = [cons3_vin.index(num)+1 for num in numeros3 if num in cons3_vin]

cons3_smin = list(total_3.loc[:, "Molecule_smin"].values)
ind3_smin = [cons3_smin.index(num)+1 for num in numeros3 if num in cons3_smin]

cons3_plan = list(total_3.loc[:, "Molecule_plan"].values)
ind3_plan = [cons3_plan.index(num)+1 for num in numeros3 if num in cons3_plan]

cons3_rdoc = list(total_3.loc[:, "Molecule_rdoc"].values)
ind3_rdoc = [cons3_rdoc.index(num)+1 for num in numeros3 if num in cons3_rdoc]

In [87]:
ecr3 = pd.DataFrame(
    {'ad3': ind3_ad,
     'vin3': ind3_vin,
     'smin3': ind3_smin,
     'plan3': ind3_plan,
     'rdoc3': ind3_rdoc
    })

In [88]:
ecr3

     ad3  vin3  smin3  plan3  rdoc3
0    120    11     14     67     13
1    117   135     38     53      5
2      2     5      4    154     46
3     91    28     50    102    111
4     94   130    114    138    112
..   ...   ...    ...    ...    ...
150  100   104    138     52     65
151  102   127     73     33    117
152   97   117    107     60     61
153  110   116    127    142    135
154   46    23     92    134    142

[155 rows x 5 columns]

In [89]:
ecr3=ecr3.apply(lambda x: np.exp(-x/20)/20, axis=1)
ecr3["ECR"] = ecr3.sum(axis=1)
ecr3["Molecule"]=list(range(1, 156))

In [90]:
ecr3

          ad3      vin3     smin3     plan3     rdoc3       ECR  Molecule
0    0.000124  0.028847  0.024829  0.001754  0.026102  0.081657         1
1    0.000144  0.000059  0.007478  0.003533  0.038940  0.050154         2
2    0.045242  0.038940  0.040937  0.000023  0.005013  0.130154         3
3    0.000528  0.012330  0.004104  0.000305  0.000194  0.017462         4
4    0.000455  0.000075  0.000167  0.000050  0.000185  0.000933         5
..        ...       ...       ...       ...       ...       ...       ...
150  0.000337  0.000276  0.000050  0.003714  0.001939  0.006316       151
151  0.000305  0.000087  0.001300  0.009602  0.000144  0.011438       152
152  0.000391  0.000144  0.000237  0.002489  0.002368  0.005630       153
153  0.000204  0.000151  0.000087  0.000041  0.000059  0.000543       154
154  0.005013  0.015832  0.000503  0.000062  0.000041  0.021450       155

[155 rows x 7 columns]

In [91]:
labelecr_3=index_3.drop_duplicates(subset=['Label']).drop(columns=['Molecule'])
labelecr_3["Molecule"]=list(range(1, 156))

In [92]:
ecr3=ecr3[['ECR','Molecule']]
ecr3=labelecr_3.merge(ecr3, on='Molecule', how='left')

In [93]:
ecr3=ecr3.sort_values(by=['ECR'],ascending=False)
ecr3['Molecule_primera']=ecr3['Molecule'].apply(lambda x: x*3)
ecr3['Molecule_segunda']=ecr3['Molecule'].apply(lambda x: x*3-1)
ecr3['Molecule_tercera']=ecr3['Molecule'].apply(lambda x: x*3-2)

In [94]:
ecr3.head(n=20)

,Label,Molecule,ECR,Molecule_primera,Molecule_segunda,Molecule_tercera
12,52944904,13,0.170579,39,38,37
5,76325328,6,0.150728,18,17,16
51,2733787,52,0.142058,156,155,154
2,118707521,3,0.130154,9,8,7
79,118328,80,0.121072,240,239,238
52,2733335,53,0.115933,159,158,157
13,52944903,14,0.115706,42,41,40
122,ZINC000101361998,123,0.100447,369,368,367
11,52948856,12,0.098555,36,35,34
23,44630437,24,0.098097,72,71,70
89,29327,90,0.096527,270,269,268
56,447448,57,0.090071,171,170,169
87,82313,88,0.089189,264,263,262
47,5284365,48,0.086288,144,143,142
40,7067772,41,0.085989,123,122,121
80,112106,81,0.085696,243,242,241
24,44341508,25,0.082741,75,74,73
0,134695375,1,0.081657,3,2,1
35,12600646,36,0.080997,108,107,106
91,24139,92,0.075919,276,275,274

In [95]:
ecr3.to_csv('ecr3N.csv')