## Parsing Output CSV Vina

In [10]:
##Importing packages

import pandas as pd
import numpy as np

In [11]:
##Reading file

df = pd.read_csv('final_value_vina.csv', delimiter=",")
df

      Ligand  affinity_(kcal/mol)  rmsd_lb  rmsd_ub
0     Lig100                 -5.9    0.000    0.000
1     Lig100                 -5.7    4.522    7.404
2     Lig100                 -5.6    2.902    4.097
3     Lig100                 -5.5    3.846    5.610
4     Lig100                 -5.4    3.548    6.936
...      ...                  ...      ...      ...
9520    Lig9                 -7.0    7.352   11.269
9521    Lig9                 -6.8    5.616    6.596
9522    Lig9                 -6.8    5.349    5.917
9523    Lig9                 -6.8    5.692    6.906
9524    Lig9                 -6.7    4.150    8.722

[9525 rows x 4 columns]

In [12]:
df.sort_values(by='affinity_(kcal/mol)')

      Ligand  affinity_(kcal/mol)  rmsd_lb  rmsd_ub
9065    Lig7                 -8.6    0.000    0.000
639    Lig12                 -8.5    0.000    0.000
6190  Lig380                 -8.4    0.000    0.000
1079   Lig14                 -8.3    0.000    0.000
9285    Lig8                 -8.3    0.000    0.000
...      ...                  ...      ...      ...
7644  Lig445                 -3.7    2.685    4.442
6469  Lig392                 -3.7    7.331    8.125
7665  Lig446                 -3.7    7.770    9.482
7684  Lig447                 -3.6    2.040    2.600
7685  Lig447                 -3.6    2.095    3.908

[9525 rows x 4 columns]

In [13]:
df.to_csv('3_vina.csv')